package POJO;


import DAO.DAOLogin;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 * Login generated by hbm2java
 */
@ManagedBean
public class Login  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String password;

    public String login_user() {
        DAOLogin uDao = new DAOLogin();
        List<Login> us = uDao.getBy(email, password);
        try {
            if (us != null) {
                email = us.get(0).email;
                password = us.get(0).password;
                return "List";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return "Login_error";
    }
 
     
     
    public Login() {
    }

    public Login(String email, String password) {
       this.email = email;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


